# https://docs.travis-ci.com/user/customizing-the-build/

sudo: false
language: node_js
node_js:
  - "4"
  - "5"
  - "6"
cache: yarn
branches:
  only:
    - master
    - /^greenkeeper-.*$/
matrix:
  fast_finish: true
script: yarn start ci
